### ISSUE TITLE
Create "Status" Button for Mobile App and Implement Get API Call to Retrieve Token and User Info

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#157]
As per the requirement, need to create a new button called "Status" on the mobile app. This button should be used to retrieve the user's token and information from the server using a GET API call.

**Task Checklist**:

- [ ] Create a new button called "proceed" on the mobile app after getting the user-id.
- [ ] [Implement a GET API call to retrieve the user's token and information](https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/qr-code-auth)
- [ ] Display the retrieved token and user info on the mobile app interface ie on the home screen for now.

**Additional Information:**

The server endpoint for the API call will be provided by the backend team.
The token and user info should be securely stored on the client side using appropriate encryption techniques.
