### ISSUE TITLE
Sign In with Github

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#199]
Implement a 'Sign In with GitHub' button in the mobile app. When activated, this button should open the default web browser, directing users to the GitHub login page. After users input their credentials and are authorized, GitHub should redirect them back to the app with an authentication token. This process should replicate the existing workflow found on the welcome site. 

Drop an ETA for completion is requested for the assigned owner before starting.

**Comment by shreya-mishra** [comment]
### **SignIn with github Flow**

This is the scenario which involves implementing OAuth-based GitHub sign-in functionality in a mobile app, specifically handling the redirection to GitHub's OAuth page, managing callbacks, and dealing with scenarios when the app is or isn't installed. Additionally, we're addressing potential issues with how the backend handles redirects and the user agent header.

To begin with, when a user clicks the "Sign in with GitHub" button in RDS mobile app, the app should initiate the OAuth flow. This typically involves opening the user's mobile browser and redirecting them to GitHub's OAuth page. This is a standard practice in OAuth-based authentication, ensuring security and user trust.

The callback URL after successful GitHub authentication depends on whether it's the old signup flow or the new one. In the old flow, it's "www.realdevsquad.com," and in the new flow, it's "my.realdevsquad.com." These URLs are where GitHub will redirect the user's browser after authentication.

Now, a challenge arises: How do you redirect the user back to the RDS mobile app with a session token? here comes the "rds-session cookie," which suggests a session management approach. After GitHub authentication, when the user is redirected to your site (www or my), our backend should create this session and return it to the client, possibly in a response header or as a response payload.

For mobile browsers, you want to create a seamless user experience. If the RDS mobile app is installed, the user should be given the option to continue in the app. If it's not installed, you should redirect them to the Play Store or App Store for installation. If they choose not to continue, they should stay on the browser website.

Here comes the part about detecting where the /callback request is coming from. We can check the user agent header, which usually contains information about the client's device and browser. However, this method has limitations because it might not distinguish between requests from the RDS mobile app's in-app browser and requests from external mobile browsers. To address this,we can pass a key in the request parameters when hitting the GitHub authentication URL or we can access the headers in backend and get the user-agent or may be some other query parameters in headers which we can use(need to check)

This additional key allows our backend to differentiate between requests initiated from the RDS mobile app and those from external browsers. This is a reasonable approach to ensure that only legitimate RDS app users are redirected to the app after GitHub authentication.

In summary, the flow involves initiating the OAuth flow with GitHub, redirecting the user to GitHub's OAuth page, and handling callbacks based on the old or new signup flow. You'll use session management to maintain user sessions and return a session token. To create a seamless experience, detect whether the RDS app is installed and offer the option to continue in the app or stay in the browser. The user agent header might not be sufficient for this, so you'll pass a key in the request parameters to help your backend distinguish between RDS app-initiated and external browser-initiated requests. This approach ensures a secure and user-friendly authentication process in your RDS mobile app.

![image](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/ea5fcdd9-d6f0-4c78-8bae-dd033902007c)

In the above flowchart
-     The process starts with the user clicking the "Sign in with GitHub" button in the mobile app.
-     It then redirects the user to GitHub's OAuth flow in a mobile browser.
-     After successful authentication, GitHub redirects the user back to your RDS backend, which may have different flows for old and new signups.
-     The backend checks if the RDS app is installed on the user's device.
-     If the app is installed, it displays an option to continue in the app; otherwise, it redirects the user to the app store for installation or keeps them on the website based on their choice.
-     The user makes a decision (continue in app or stay on the website), leading to different outcomes.

Certainly, if we want to differentiate between login attempts from the RDS mobile app and login attempts from a generic mobile browser when the User-Agent header alone is not sufficient, you can use query parameters in the GitHub OAuth callback URL.

Here's an updated Mermaid flowchart to illustrate this approach:
![image](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/3c0ef448-d214-463e-99ad-657c5c33941c)

In this flowchart:

-    The process starts at "Start."
- Users initiate GitHub login, which redirects them to GitHub's OAuth flow ("GitHubLogin").
- After the GitHub OAuth process is complete, a callback is made to your "HandleGitHubCallback" endpoint.
- In the "HandleGitHubCallback" endpoint, you check query parameters to determine the source of the request. If the "FromApp" query parameter is set to "true," it redirects to the app ("RedirectToApp"). If it's set to "false" or not present, it redirects to the website ("RedirectToWebsite").

This approach allows us to use query parameters as a signal to distinguish between login attempts from the RDS mobile app and those from a generic mobile browser, giving you more control over the redirection process.

**Comment by shreya-mishra** [comment]
**Task breakdown**

- [x] Redirection to github Gtihub oAuth in mobile browser and get the user verify it.
- [x] Create a deeplink and verify it with the browser by connecting with any website as a rfc
- [x] setup www site on local and then configure the flow of /goto, /join and realdevsquad website
- [x] Made changes to backend so that if we are logging in from mobile backend should know that its  mobile app otherwise its website by checking the user-agent in callback.
- [x] Check any other parameter which can identify if the request is coming from RDS mobile app or mobile browser if that doesnt workout may be other way - 2
- [x] Declare the Web association once the www site and my site deployed. - 0.5
- [x] **Blocker** : At once only one website can be configure with mobile app and right now I am working on my-site - 1
- [x] now it should redirect to the app with cookie, will be sending it via backend in same redirection url. - 1
- [ ] use that cookie/token to store in mobile app as token - 1
- [ ] Use that token to call all the api's - 1
- [ ] buffer - 3days
**total** - 5 days + review and resolve comments(2day) 

= 6days

ETA:  22 Sept
updated ETA: added 11 days from today(19 Sept)
ETA: 30 Sept
wasted 3 days as I was not well and then worked on flow diagram to get better understanding - 

**Blockers can be**
- old and new signup flow website cant configure with mobile app. As at one time only one website can be associated with a particular mobile app (have to look into this more)
- Old and new signup flow depends on inComplete user details , if it is false then my-site or else www site

**Comment by sahsisunny** [comment]
Mermaid Diagram

```mermaid
sequenceDiagram
    participant User as User
    participant MobileApp as Mobile App
    participant MobileBrowser as Mobile Browser
    participant GitHub as GitHub
    participant RealDevSquad as RealDevSquad

    User->>MobileApp: Step 1: Clicks on Sign in with GitHub Button
    MobileApp->>MobileBrowser: Step 2: Redirect to GitHub OAuth (client_id)
    MobileBrowser->>MobileBrowser: Step 3: Automatically opens GitHub login URL
    MobileBrowser->>GitHub: Step 4: Redirect to GitHub OAuth authorize URL (client_id)
    GitHub->>MobileBrowser: Step 5: Redirect to RealDevSquad
    MobileBrowser->>RealDevSquad: Step 6: Redirect to RealDevSquad's assets links
    RealDevSquad-->>MobileBrowser: Step 7: If cookie is not set
    RealDevSquad->>MobileApp: Redirect to Mobile App Signup Page
    RealDevSquad-->>MobileBrowser: Step 8: If cookie is set
    RealDevSquad->>MobileApp: Redirect to Mobile App Home Page

```

Step 1: Clicks on Sign in with GitHub Button
- Description: The user initiates the GitHub sign-in process by clicking on the "Sign in with GitHub" button in the mobile app.
- Inputs: User interaction with the mobile app.
- Outputs: Initiates the GitHub OAuth process.

Step 2: Redirect to GitHub OAuth (client_id)
- Description: The mobile app redirects the user to the GitHub OAuth authorization page, passing along the `client_id` for identification.
- Inputs: User's action to initiate GitHub OAuth.
- Outputs: Redirects the user to GitHub's login page with `client_id`.

Step 3: Automatically opens GitHub login URL
- Description: The mobile browser automatically opens the GitHub login URL, including parameters such as `client_id`, `return_to`, `scope`, and `state`.
- Inputs: Redirect URL with OAuth parameters.
- Outputs: Opens the GitHub login page.

Step 4: Redirect to GitHub OAuth authorize URL (client_id)
- Description: The GitHub OAuth login page processes the request and redirects the user to the GitHub OAuth authorization URL with the provided `client_id`.
- Inputs: User's action to log in with GitHub.
- Outputs: Redirects the user to GitHub's OAuth authorization URL.

Step 5: Redirect to RealDevSquad
- Description: After the user authorizes the app on GitHub, they are redirected back to the RealDevSquad website.
- Inputs: User's action to authorize the app on GitHub.
- Outputs: Redirects the user to the RealDevSquad website.

Step 6: Redirect to RealDevSquad's assets links
- Description: The RealDevSquad website processes the GitHub authorization and redirects to RealDevSquad's assets links.
- Inputs: User's authorization on GitHub.
- Outputs: Redirects to RealDevSquad's assets links.

Step 7: If cookie is not set
- Description: RealDevSquad checks if a cookie is set to determine if the user is signed up.
- Inputs: The presence or absence of a cookie.
- Outputs: If no cookie is set, it redirects the user to the mobile app's signup page.

Step 8: If cookie is set
- Description: If a cookie is set, RealDevSquad determines that the user is signed up and redirects them to the mobile app's home page.
- Inputs: The presence of a cookie.
- Outputs: Redirects the user to the mobile app's home page.

**Comment by shreya-mishra** [comment]
> **Task breakdown**
> 
>     * [x]  Redirection to github Gtihub oAuth in mobile browser and get the user verify it.
> 
>     * [x]  Create a deeplink and verify it with the browser by connecting with any website as a rfc
> 
>     * [x]  setup www site on local and then configure the flow of /goto, /join and realdevsquad website
> 
>     * [x]  Made changes to backend so that if we are logging in from mobile backend should know that its  mobile app otherwise its website by checking the user-agent in callback.
> 
>     * [ ]  Check any other parameter which can identify if the request is coming from RDS mobile app or mobile browser if that doesnt workout may be other way - 2
> 
>     * [x]  Declare the Web association once the www site and my site deployed. - 0.5
> 
>     * [ ]  **Blocker** : At once only one website can be configure with mobile app and right now I am working on my-site - 1
> 
>     * [ ]  now it should redirect to the app with cookie, will be sending it via backend in same redirection url. - 1
> 
>     * [ ]  use that cookie/token to store in mobile app as token - 1
> 
>     * [ ]  Use that token to call all the api's - 1
> 
>     * [ ]  buffer - 2days
>       total - 5 days + review and resolve comments(2day)
> 
> 
> = 6days
> 
> ETA: 22 Sept + 10 days (more)
> 
> wasted 3 days as I was not well and then worked on flow diagram to get better understanding -
> 
> **Blockers can be**
> 
>     * old and new signup flow website cant configure with mobile app. As at one time only one website can be associated with a particular mobile app (have to look into this more)

**Things which I need to look into**
- [ ] on mobile browser my and www site it should give a popup to open in mobile app.
- [ ] iOS version deeplinking setup

**ps** will be doing it after the basic flow

**Comment by shreya-mishra** [comment]
**Blockers Solution**:

_Must read_ 
https://developer.apple.com/documentation/xcode/supporting-associated-domains

**Comment by shreya-mishra** [comment]
**Problem**: Check any other parameter which can identify if the request is coming from RDS mobile app or mobile browser if that doesnt workout may be other way

**solution**

we can pass utm parameter and access the same from req.query.source_utm
```

// Define the query parameters
const queryParams = {
  source_utm: 'rds-mobile-app',
  // Add other query parameters as needed
};

// Create a function to build the complete URL
function buildUrl(baseUrl, queryParams) {
  const queryString = Object.keys(queryParams)
    .map(key => `${key}=${queryParams[key]}`)
    .join('&');

  return `${baseUrl}?${queryString}`;
}

// Call the buildUrl function to create the final URL
const githubAuthUrl = buildUrl(baseUrl, queryParams);

```
