### ISSUE TITLE
Todo:  Goals App

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#288]
- [x]  #263 
- [ ] #318
- [ ] API integration to verify goals api as all the api's will authenticated and the backend is seperated from the RDS.
- [ ] Integrate the api to get all the goals and show the response in logs.
- [ ] Replace the dummy data to GET goals api response in goals card.
- [ ] Integrate the POST API to store the goals data in backend and call the same on submitting the create goals form.
- [ ] Integrate the API while swiping the cards (deletion)
- [ ] Integrate the API while swiping back the cards(undo) 

@pallabez please confirm when API contract is ready as the below are the blockers, let us know once below are unblocked. 

- [x] #317
- [x] #337
- [x] #338
- [x] #339
- [x] #340

please mark above done once above API's are live on prod or staging.

Thankyou! please reach out to me in case of any queries.

**Comment by ashifkhn** [comment]
https://github.com/Real-Dev-Squad/mobile-app/issues/317: 
This integration need 2 hours.
Things to be done in this isuue: 1. fetch goals api token and store it in the local storage to make another goal app calls.(1.5 hour)
2. Sanity testing (30 mins)

https://github.com/Real-Dev-Squad/mobile-app/issues/337: 
This integration need 2 hours.
1. Integration of the api data in the current ui

https://github.com/Real-Dev-Squad/mobile-app/issues/338:
This integration need 2-3 hours.
1. Integration with current form. Need to check the data types coming from api. Edge cases for making post req(2-3 hours)

Will Do this things in this task. If we have some more time, I'll try to integrate delete api as well.
